# Data in format of a dictionary (format = key: [index, value])
dataDict = {
    "Battery current": [0, 0],
    "Battery voltage before power switch": [1, 0],
    "Battery voltage after power switch": [2, 0],
    "LVBMS": [3, 0],
    "1st battery cell voltage": [4, 0],
    "2nd battery cell voltage": [5, 0],
    "3rd battery cell voltage": [6, 0],
    "Battery temperature": [7, 0],
    "Calibration voltages": [8, 0],
    "Cell state": [9, 0],
    "Calibration current": [10, 0],
    "Motor RPM": [11, 0],
    "Throttle Position": [12, 0],
    "Intake Air Temperature": [13, 0],
    "MAP": [14, 0],
    "Oil Temperature": [15, 0],
    "Oil Pressure": [16, 0],
    "Fuel Pressure": [17, 0],
    "Coolant Temperature": [18, 0],
    "Ignition Angle": [19, 0],
    "Coil dwell time": [20, 0],
    "Lambda sensor": [21, 0],
    "Lambda correction": [22, 0],
    "Exhaust gas temperature  1": [23, 0],
    "Exhaust gas temperature  2": [24, 0],
    "Gear selection to EMU": [25, 0],
    "EMU internal temperature": [26, 0],
    "EMU battery voltage": [27, 0],
    "Clt error": [28, 0],
    "Drive by wire position": [29, 0],
    "Drive by wire target": [30, 0],
    "Starter Request": [31, 0],
    "Gear up": [32, 0],
    "Gear down": [33, 0],
    "Clutch": [34, 0],
    "Selected MAP": [35, 0],
    "Launch control switch": [36, 0],
    "AutoShift switch": [37, 0],
    "AntiStall switch": [38, 0],
    "Radio talk turn on switch": [39, 0],
    "Fan control switch": [40, 0],
    "DRS position control switch": [41, 0],
    "Balance bar control switch": [42, 0],
    "Traction control switch": [43, 0],
    "ADU page selection switch": [44, 0],
    "Brake fluid pressure front": [45, 0],
    "Steering wheel angle sensor": [46, 0],
    "Flowmeter 1": [47, 0],
    "Flowmeter 2": [48, 0],
    "Accelerometer x axis": [49, 0],
    "Accelerometer y axis": [50, 0],
    "Accelerometer z axis": [51, 0],
    "Gyroscope x axis": [52, 0],
    "Gyroscope y axis": [53, 0],
    "Gyroscope z axis": [54, 0],
    "Front Left Wheel: Linear Potentiometer": [55, 0],
    "Front Left Wheel: Wheel Speed": [56, 0],
    "Front Left Wheel: Tyre Temperature": [57, 0],
    "Front Left Wheel: Brake Temperature": [58, 0],
    "Front Right Wheel: Linear Potentiometer": [59, 0],
    "Front Right Wheel: Wheel Speed": [60, 0],
    "Front Right Wheel: Tyre Temperature": [61, 0],
    "Front Right Wheel: Brake Temperature": [62, 0],
    "Rear Left Wheel: Linear Potentiometer": [63, 0],
    "Rear Left Wheel: Wheel Speed": [64, 0],
    "Rear Left Wheel: Tyre Temperature": [65, 0],
    "Rear Left Wheel: Brake Temperature": [66, 0],
    "Rear Right Wheel: Linear Potentiometer": [67, 0],
    "Rear Right Wheel: Wheel Speed": [68, 0],
    "Rear Right Wheel: Tyre Temperature": [69, 0],
    "Rear Right Wheel: Brake Temperature": [70, 0],
}
# Automated data dictionary generation
# lines = open("Dane.txt")
# for index, line in enumerate(lines):
#     print(f"\"{line[0:len(line)-1]}\": [{index}, 0], ")

